name: worker_service_example
publish_to: none
description: Demonstrates how to use the worker_service plugin
environment: 
  sdk: '>=2.5.0 <3.0.0'
dependencies: 
  permission_handler: ^9.2.0
  dorker: ^0.1.4
  js: ^0.6.4
  sunny_dart: 
    path: /Users/ericm/sunny/player_rank/packages/sunny_dart
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^2.1.10
  build_config: ^1.0.0
  worker_service: 
    path: /Users/ericm/sunny/player_rank/packages/worker_service
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
