name: worker_service
version: 0.7.4
homepage: https://github.com/SunnyApp/worker_service
description: A flutter package that works for native/web, and allows the creation of workers that offload work into a potentially parallel space
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  async: ^2.11.0
  collection: ^1.17.2
  equatable: ^2.0.5
  js: ^0.6.7
  logging: 1.2.0
  meta: ^1.9.1
  uuid: ^3.0.7
  isolates: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/isolate
  logging_config: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/logging_config
  dartxx: 
    path: /Users/ericm/aesthetika/checkout/ericmartineau/dartxx
dev_dependencies: 
  pedantic: ^1.11.1
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - ./lib/bootstrap_dev.js
    - ./lib/bootstrap_prod.js
