name: grunt_web_worker_gen
description: Generates web workers
version: 0.7.2+14

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^2.0.0
  build: ^2.0.3
  build_config: ^1.0.0
  build_runner: ^2.0.6
  #build_web_compilers: ^3.2.0
  flutter_degen: ^0.6.0+4
  logging: ^1.0.1
  pedantic: ^1.11.1
  recase: ^4.0.0
  meta: ^1.7.0
  source_gen: ^1.0.5
  uri: ^1.0.0
  worker_service: ^0.7.2+14
dev_dependencies:
  test: ^1.17.10
