name: grunt_web_worker_gen
publish_to: none
description: Generates web workers
environment: 
  sdk: '>=2.5.0 <3.0.0'
dependencies: 
  analyzer: ^5.0.0
  build: ^1.6.1
  build_config: ^1.1.0
  build_runner: ^2.2.1
  build_web_compilers: ^2.16.1
  logging: ^1.0.2
  pedantic: ^1.11.1
  recase: ^4.0.0
  source_gen: ^0.9.10+1
  flutter_degen: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/flutter_degen
  uri: 
    path: /Users/ericm/sunny/local_plugins/uri.dart
  worker_service: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/worker_service
dev_dependencies: 
  test: ^1.15.7
dependency_overrides: 
  flutter_degen: 
    path: ../../flutter_degen
  worker_service: 
    path: ../
  sunny_dart: 
    path: ../../sunny_dart
